name: Build Junkcoin-Qt on Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 安装 Chocolatey 包管理器
    - name: Install Chocolatey
      run: |
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
        Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      
    # 将 Chocolatey 的 bin 目录添加到 PATH 中
    - name: Update PATH for Chocolatey
      run: |
        $env:PATH += ";C:\ProgramData\chocolatey\bin"

    # 安装 Visual Studio 构建工具和 Qt
    - name: Install Build Tools and Qt
      run: |
        choco install visualstudio2019buildtools --params "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows10SDK.19041"

    - name: Install Qt windows
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.2.*'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'

    # 验证 Qt 安装路径
    #- name: Verify Qt installation
    # run: dir C:\Qt
    
    
    - name: Set up Visual Studio environment
      shell: pwsh
      run: |
        Start-Process "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" -ArgumentList "x64" -Wait -NoNewWindow

    - name: Build with qmake
      shell: pwsh
      run: |
        $env:PATH += ";D:\a\Junkcoin\Qt\6.2.*/msvc2019_64\bin"
        $env:INCLUDE += ";D:\a\Junkcoin\Qt\6.2.*/msvc2019_64\include"
        $env:LIB += ";D:\a\Junkcoin\Qt\6.2.*/msvc2019_64\lib"
        & "D:\a\Junkcoin\Qt\6.2.*/msvc2019_64\bin\qmake.exe" junkcoin-qt-windows.pro
        & "nmake"

    # 将编译产物保存为 GitHub Actions 的工件，以便下载
    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: junkcoin-qt-build
        path: ./release/  # 根据你的项目结构调整路径
